language: python
sudo: required
dist: xenial
services:
  - postgresql
python:
  - 3.6
install:
  - pipenv run python -m pip install -U pip
  - pipenv install --dev --ignore-pipfile
before_script:
  - cp config/.treasurer_tools config/treasurer_tools.env
  - psql -c "CREATE DATABASE treasurer_tools;" -U postgres
  - psql -c "CREATE USER treasurer_tools WITH PASSWORD 'treasurer_tools';" -U postgres
  - psql -c "ALTER ROLE treasurer_tools SET client_encoding TO 'utf8';" -U postgres
  - psql -c "ALTER ROLE treasurer_tools SET default_transaction_isolation TO 'read committed';" -U postgres
  - psql -c "ALTER ROLE treasurer_tools SET timezone TO 'UTC';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE treasurer_tools TO treasurer_tools;" -U postgres
  - psql -c "ALTER USER treasurer_tools CREATEDB;" -U postgres
script:
  - pipenv run pytest
