# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transaction', models.DateField(help_text='The date of the transaction', verbose_name='transaction date')),
                ('description_bank', models.CharField(help_text='Description of the transaction as per the bank statement', max_length=100, verbose_name='bank description')),
                ('description_user', models.CharField(blank=True, help_text='A user-specified description of the transaction', max_length=100, null=True, verbose_name='custom description')),
                ('amount_debit', models.DecimalField(decimal_places=2, default=0, help_text='The debit (withdrawal) amount of the transaction', max_digits=12, verbose_name='debit amount')),
                ('amount_credit', models.DecimalField(decimal_places=2, default=0, help_text='The credit (deposit) amount of the transaction', max_digits=12, verbose_name='credit amount')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBankTransaction',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_transaction', models.DateField(help_text='The date of the transaction', verbose_name='transaction date')),
                ('description_bank', models.CharField(help_text='Description of the transaction as per the bank statement', max_length=100, verbose_name='bank description')),
                ('description_user', models.CharField(blank=True, help_text='A user-specified description of the transaction', max_length=100, null=True, verbose_name='custom description')),
                ('amount_debit', models.DecimalField(decimal_places=2, default=0, help_text='The debit (withdrawal) amount of the transaction', max_digits=12, verbose_name='debit amount')),
                ('amount_credit', models.DecimalField(decimal_places=2, default=0, help_text='The credit (deposit) amount of the transaction', max_digits=12, verbose_name='credit amount')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical bank transaction',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalStatement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_start', models.DateField(help_text='The first date the statement applies to', verbose_name='start date')),
                ('date_end', models.DateField(help_text='The last date the statement applies to', verbose_name='end date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_institutions.Account')),
            ],
            options={
                'verbose_name': 'historical statement',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(help_text='The first date the statement applies to', verbose_name='start date')),
                ('date_end', models.DateField(help_text='The last date the statement applies to', verbose_name='end date')),
                ('account', models.ForeignKey(help_text='The account this statement belong to', on_delete=django.db.models.deletion.PROTECT, to='bank_institutions.Account')),
            ],
        ),
    ]
