# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 22:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        ('documents', '0003_auto_20171210_1447'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text='The account number/reference for this account', max_length=100)),
                ('name', models.CharField(help_text='The name of the account', max_length=100)),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], help_text='The account status', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='am_attachment', to='documents.Attachment')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transaction', models.DateField(help_text='The date of the transaction')),
                ('description_bank', models.CharField(help_text='Description of the transaction as per the bank statement', max_length=100)),
                ('description_user', models.CharField(help_text='A user-specified description of the transaction', max_length=100)),
                ('amount_debit', models.DecimalField(decimal_places=2, help_text='The debit (withdrawal) amount of the transaction', max_digits=12)),
                ('amount_credit', models.DecimalField(decimal_places=2, help_text='The credit (deposit) amount of the transaction', max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('account_number', models.CharField(help_text='The account number/reference for this account', max_length=100)),
                ('name', models.CharField(help_text='The name of the account', max_length=100)),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], help_text='The account status', max_length=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical account',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAttachmentMatch',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('attachment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.Attachment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_transactions.BankTransaction')),
            ],
            options={
                'verbose_name': 'historical attachment match',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBankTransaction',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_transaction', models.DateField(help_text='The date of the transaction')),
                ('description_bank', models.CharField(help_text='Description of the transaction as per the bank statement', max_length=100)),
                ('description_user', models.CharField(help_text='A user-specified description of the transaction', max_length=100)),
                ('amount_debit', models.DecimalField(decimal_places=2, help_text='The debit (withdrawal) amount of the transaction', max_digits=12)),
                ('amount_credit', models.DecimalField(decimal_places=2, help_text='The credit (deposit) amount of the transaction', max_digits=12)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical bank transaction',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalInstitution',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bank/financial institution', max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=30)),
                ('fax', models.CharField(max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical institution',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalReconciliationMatch',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('bank_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_transactions.BankTransaction')),
                ('financial_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transactions.Transaction')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical reconciliation match',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalStatement',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_start', models.DateField(help_text='The first date the statement applies to')),
                ('date_end', models.DateField(help_text='The last date the statement applies to')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_transactions.Account')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical statement',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bank/financial institution', max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=30)),
                ('fax', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rm_bank_transaction', to='bank_transactions.BankTransaction')),
                ('financial_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rm_financial_transaction', to='transactions.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(help_text='The first date the statement applies to')),
                ('date_end', models.DateField(help_text='The last date the statement applies to')),
                ('account', models.ForeignKey(help_text='The account this statement belong to', on_delete=django.db.models.deletion.PROTECT, to='bank_transactions.Account')),
            ],
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='institution',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_transactions.Institution'),
        ),
        migrations.AddField(
            model_name='attachmentmatch',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='am_bank_transaction', to='bank_transactions.BankTransaction'),
        ),
        migrations.AddField(
            model_name='account',
            name='institution',
            field=models.ForeignKey(help_text='The bank this account is associated with', on_delete=django.db.models.deletion.PROTECT, to='bank_transactions.Institution'),
        ),
    ]
