# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(help_text='The account number/reference for this account', max_length=100)),
                ('name', models.CharField(help_text='The name of the account', max_length=100)),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='a', help_text='The account status', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='am_attachment', to='documents.Attachment')),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transaction', models.DateField(help_text='The date of the transaction', verbose_name='transaction date')),
                ('description_bank', models.CharField(help_text='Description of the transaction as per the bank statement', max_length=100, verbose_name='bank description')),
                ('description_user', models.CharField(blank=True, help_text='A user-specified description of the transaction', max_length=100, null=True, verbose_name='user description')),
                ('amount_debit', models.DecimalField(decimal_places=2, default=0, help_text='The debit (withdrawal) amount of the transaction', max_digits=12, verbose_name='debit amount')),
                ('amount_credit', models.DecimalField(decimal_places=2, default=0, help_text='The credit (deposit) amount of the transaction', max_digits=12, verbose_name='credit amount')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bank/financial institution', max_length=250)),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=30, verbose_name='phone number')),
                ('fax', models.CharField(max_length=30, verbose_name='fax number')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(help_text='The first date the statement applies to', verbose_name='start date')),
                ('date_end', models.DateField(help_text='The last date the statement applies to', verbose_name='end date')),
                ('account', models.ForeignKey(help_text='The account this statement belong to', on_delete=django.db.models.deletion.PROTECT, to='bank_transactions.Account')),
            ],
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='statement',
            field=models.ForeignKey(help_text='The statement this this transaction applies to', on_delete=django.db.models.deletion.CASCADE, to='bank_transactions.Statement'),
        ),
        migrations.AddField(
            model_name='attachmentmatch',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='am_bank_transaction', to='bank_transactions.Statement'),
        ),
        migrations.AddField(
            model_name='account',
            name='institution',
            field=models.ForeignKey(help_text='The bank this account is associated with', on_delete=django.db.models.deletion.CASCADE, to='bank_transactions.Institution'),
        ),
    ]
