# Generated by Django 2.2.6 on 2019-11-09 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalbanktransaction',
            name='statement',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The statement this this transaction applies to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_transactions.Statement', verbose_name='bank statement'),
        ),
        migrations.AlterField(
            model_name='historicalstatement',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The account this statement belong to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_institutions.Account'),
        ),
    ]
