# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='statement',
            field=models.ForeignKey(default=1, help_text='The statement this this transaction applies to', on_delete=django.db.models.deletion.CASCADE, to='bank_transactions.Statement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbanktransaction',
            name='statement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_transactions.Statement'),
        ),
    ]
