# Generated by Django 5.1.5 on 2025-01-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0002_auto_20191109_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbanktransaction',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical bank transaction', 'verbose_name_plural': 'historical bank transactions'},
        ),
        migrations.AlterModelOptions(
            name='historicalstatement',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical statement', 'verbose_name_plural': 'historical statements'},
        ),
        migrations.AlterField(
            model_name='historicalbanktransaction',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalstatement',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
