# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 03:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0002_historicalaccount_historicalattachmentmatch_historicalbanktransaction_historicalinstitution_historic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='attachmentmatch',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='attachmentmatch',
            name='statement',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalaccount',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='historicalattachmentmatch',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='historicalattachmentmatch',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalattachmentmatch',
            name='statement',
        ),
        migrations.RemoveField(
            model_name='historicalinstitution',
            name='history_user',
        ),
        migrations.AlterField(
            model_name='historicalstatement',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_institutions.Account'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='account',
            field=models.ForeignKey(help_text='The account this statement belong to', on_delete=django.db.models.deletion.PROTECT, to='bank_institutions.Account'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AttachmentMatch',
        ),
        migrations.DeleteModel(
            name='HistoricalAccount',
        ),
        migrations.DeleteModel(
            name='HistoricalAttachmentMatch',
        ),
        migrations.DeleteModel(
            name='HistoricalInstitution',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
