# Generated by Django 2.0.3 on 2018-07-14 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reconciliation', '0006_auto_20180714_1457'),
        ('bank_transactions', '0002_auto_20180216_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='reconciled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank_reconciliation.ReconciliationGroup'),
        ),
        migrations.AddField(
            model_name='historicalbanktransaction',
            name='reconciled',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_reconciliation.ReconciliationGroup'),
        ),
    ]
