# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0002_auto_20171226_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='a', help_text='The account status', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='a', help_text='The account status', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalinstitution',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalinstitution',
            name='fax',
            field=models.CharField(max_length=30, verbose_name='fax number'),
        ),
        migrations.AlterField(
            model_name='historicalinstitution',
            name='name',
            field=models.CharField(help_text='Name of the bank/financial institution', max_length=250),
        ),
        migrations.AlterField(
            model_name='historicalinstitution',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='institution',
            name='fax',
            field=models.CharField(max_length=30, verbose_name='fax number'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(help_text='Name of the bank/financial institution', max_length=250),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='phone number'),
        ),
    ]
