# Generated by Django 2.0.3 on 2018-07-14 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0003_auto_20180714_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='reconciled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banktransactions', to='bank_reconciliation.ReconciliationGroup'),
        ),
    ]
