# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 17:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0003_auto_20180210_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='description_user',
            field=models.CharField(blank=True, help_text='A user-specified description of the transaction', max_length=100, null=True, verbose_name='custom description'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='statement',
            field=models.ForeignKey(help_text='The statement this this transaction applies to', on_delete=django.db.models.deletion.CASCADE, to='bank_transactions.Statement', verbose_name='bank statement'),
        ),
        migrations.AlterField(
            model_name='historicalbanktransaction',
            name='description_user',
            field=models.CharField(blank=True, help_text='A user-specified description of the transaction', max_length=100, null=True, verbose_name='custom description'),
        ),
    ]
