# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 21:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0008_auto_20180114_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreconciliationmatch',
            name='bank_transaction',
        ),
        migrations.RemoveField(
            model_name='historicalreconciliationmatch',
            name='financial_transaction',
        ),
        migrations.RemoveField(
            model_name='historicalreconciliationmatch',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='reconciliationmatch',
            name='bank_transaction',
        ),
        migrations.RemoveField(
            model_name='reconciliationmatch',
            name='financial_transaction',
        ),
        migrations.DeleteModel(
            name='HistoricalReconciliationMatch',
        ),
        migrations.DeleteModel(
            name='ReconciliationMatch',
        ),
    ]
