# Generated by Django 2.0.3 on 2018-07-15 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_full', models.CharField(help_text='The full name of the branch', max_length=255)),
                ('name_short', models.CharField(help_text='The abbreviated name of the branch', max_length=255)),
                ('contact_name', models.CharField(blank=True, help_text='The main contact for the branch', max_length=255, null=True)),
                ('address', models.TextField(blank=True, help_text='The full address of the branch', max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, help_text='The main phone number for the branch', max_length=20, null=True)),
                ('fax', models.CharField(blank=True, help_text='The main fax number for the branch', max_length=20, null=True)),
                ('email', models.CharField(blank=True, help_text='The main email for the branch', max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, help_text='A logo for the branch', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='BranchMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branch_details.Branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBranch',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name_full', models.CharField(help_text='The full name of the branch', max_length=255)),
                ('name_short', models.CharField(help_text='The abbreviated name of the branch', max_length=255)),
                ('contact_name', models.CharField(blank=True, help_text='The main contact for the branch', max_length=255, null=True)),
                ('address', models.TextField(blank=True, help_text='The full address of the branch', max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, help_text='The main phone number for the branch', max_length=20, null=True)),
                ('fax', models.CharField(blank=True, help_text='The main fax number for the branch', max_length=20, null=True)),
                ('email', models.CharField(blank=True, help_text='The main email for the branch', max_length=255, null=True)),
                ('logo', models.TextField(blank=True, help_text='A logo for the branch', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical branch',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
