# Generated by Django 2.0.3 on 2018-07-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch_details', '0002_auto_20180707_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='member',
        ),
    ]
