# Generated by Django 2.0.3 on 2018-07-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_details', '0003_remove_branch_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(blank=True, help_text='The full address of the branch', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='contact_name',
            field=models.CharField(blank=True, help_text='The main contact for the branch', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='email',
            field=models.CharField(blank=True, help_text='The main email for the branch', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='fax',
            field=models.CharField(blank=True, help_text='The main fax number for the branch', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='logo_large',
            field=models.ImageField(blank=True, help_text='A logo for the branch', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='branch',
            name='logo_small',
            field=models.ImageField(blank=True, help_text='A reduced width logo for smaller screens', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, help_text='The main phone number for the branch', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='address',
            field=models.TextField(blank=True, help_text='The full address of the branch', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='contact_name',
            field=models.CharField(blank=True, help_text='The main contact for the branch', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='email',
            field=models.CharField(blank=True, help_text='The main email for the branch', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='fax',
            field=models.CharField(blank=True, help_text='The main fax number for the branch', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='logo_large',
            field=models.TextField(blank=True, help_text='A logo for the branch', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='logo_small',
            field=models.TextField(blank=True, help_text='A reduced width logo for smaller screens', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='phone',
            field=models.CharField(blank=True, help_text='The main phone number for the branch', max_length=20, null=True),
        ),
    ]
