# Generated by Django 2.0.3 on 2018-07-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch_details', '0004_auto_20180707_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='logo_large',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='historicalbranch',
            old_name='logo_large',
            new_name='logo',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='logo_small',
        ),
        migrations.RemoveField(
            model_name='historicalbranch',
            name='logo_small',
        ),
    ]
