# Generated by Django 2.0.3 on 2018-07-15 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, help_text='The account number/reference for this account', max_length=100, null=True)),
                ('name', models.CharField(help_text='The name of the account', max_length=100)),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='a', help_text='The account status', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, help_text='The account number/reference for this account', max_length=100, null=True)),
                ('name', models.CharField(help_text='The name of the account', max_length=100)),
                ('status', models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='a', help_text='The account status', max_length=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical account',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalInstitution',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bank/financial institution', max_length=250)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='phone number')),
                ('fax', models.CharField(blank=True, max_length=30, null=True, verbose_name='fax number')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical institution',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the bank/financial institution', max_length=250)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='phone number')),
                ('fax', models.CharField(blank=True, max_length=30, null=True, verbose_name='fax number')),
            ],
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='institution',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_institutions.Institution'),
        ),
        migrations.AddField(
            model_name='account',
            name='institution',
            field=models.ForeignKey(help_text='The bank this account is associated with', on_delete=django.db.models.deletion.CASCADE, to='bank_institutions.Institution'),
        ),
    ]
