# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 04:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinstitution',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='institution',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_institutions.Institution'),
        ),
        migrations.AddField(
            model_name='account',
            name='institution',
            field=models.ForeignKey(help_text='The bank this account is associated with', on_delete=django.db.models.deletion.CASCADE, to='bank_institutions.Institution'),
        ),
    ]
