# Generated by Django 5.1.5 on 2025-01-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_institutions', '0002_auto_20191109_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalaccount',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical account', 'verbose_name_plural': 'historical accounts'},
        ),
        migrations.AlterModelOptions(
            name='historicalinstitution',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical institution', 'verbose_name_plural': 'historical institutions'},
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalinstitution',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
