# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 05:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_codes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalfinancialcodesystem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfinancialcodegroup',
            name='budget_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_codes.BudgetYear'),
        ),
        migrations.AddField(
            model_name='historicalfinancialcodegroup',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfinancialcode',
            name='financial_code_group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_codes.FinancialCodeGroup'),
        ),
        migrations.AddField(
            model_name='historicalfinancialcode',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalbudgetyear',
            name='financial_code_system',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_codes.FinancialCodeSystem'),
        ),
        migrations.AddField(
            model_name='historicalbudgetyear',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialcodegroup',
            name='budget_year',
            field=models.ForeignKey(help_text='The budget year that this group applies to', on_delete=django.db.models.deletion.PROTECT, to='financial_codes.BudgetYear'),
        ),
        migrations.AddField(
            model_name='financialcode',
            name='financial_code_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial_codes.FinancialCodeGroup'),
        ),
        migrations.AddField(
            model_name='budgetyear',
            name='financial_code_system',
            field=models.ForeignKey(help_text='The financial code system that this budget year applies to', on_delete=django.db.models.deletion.PROTECT, to='financial_codes.FinancialCodeSystem'),
        ),
    ]
