# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_codes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcodegroup',
            name='type',
            field=models.CharField(choices=[('e', 'Expense'), ('r', 'Revenue')], default='e', max_length=1),
        ),
        migrations.AddField(
            model_name='historicalfinancialcodegroup',
            name='type',
            field=models.CharField(choices=[('e', 'Expense'), ('r', 'Revenue')], default='e', max_length=1),
        ),
        migrations.AlterField(
            model_name='financialcode',
            name='code_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financial_codes.FinancialCodeGroup'),
        ),
        migrations.AlterField(
            model_name='financialcodegroup',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='a', help_text='Current status of this code system', max_length=1),
        ),
        migrations.AlterField(
            model_name='financialcodesystem',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='a', help_text='Current status of this code system', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalfinancialcodegroup',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='a', help_text='Current status of this code system', max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalfinancialcodesystem',
            name='status',
            field=models.CharField(choices=[('a', 'Active'), ('i', 'Inactive')], default='a', help_text='Current status of this code system', max_length=1),
        ),
    ]
