# Generated by Django 5.1.5 on 2025-01-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_codes', '0003_add_submission_setting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbudgetyear',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical budget year', 'verbose_name_plural': 'historical budget years'},
        ),
        migrations.AlterModelOptions(
            name='historicalfinancialcode',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical financial code', 'verbose_name_plural': 'historical financial codes'},
        ),
        migrations.AlterModelOptions(
            name='historicalfinancialcodegroup',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical financial code group', 'verbose_name_plural': 'historical financial code groups'},
        ),
        migrations.AlterModelOptions(
            name='historicalfinancialcodesystem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical financial code system', 'verbose_name_plural': 'historical financial code systems'},
        ),
        migrations.AlterField(
            model_name='historicalbudgetyear',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfinancialcode',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfinancialcodegroup',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfinancialcodesystem',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
