# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_codes', '0007_auto_20180106_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetyear',
            name='financial_code_system',
            field=models.ForeignKey(help_text='The financial code system that this budget year applies to', on_delete=django.db.models.deletion.PROTECT, to='financial_codes.FinancialCodeSystem'),
        ),
        migrations.AlterField(
            model_name='financialcodegroup',
            name='budget_year',
            field=models.ForeignKey(help_text='The budget year that this group applies to', on_delete=django.db.models.deletion.PROTECT, to='financial_codes.BudgetYear'),
        ),
    ]
