# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0003_auto_20171228_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='amount_credit',
            field=models.DecimalField(decimal_places=2, help_text='The credit (deposit) amount of the transaction', max_digits=12, verbose_name='credit amount'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='amount_debit',
            field=models.DecimalField(decimal_places=2, help_text='The debit (withdrawal) amount of the transaction', max_digits=12, verbose_name='debit amount'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='date_transaction',
            field=models.DateField(help_text='The date of the transaction', verbose_name='transaction date'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='description_bank',
            field=models.CharField(help_text='Description of the transaction as per the bank statement', max_length=100, verbose_name='bank description'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='description_user',
            field=models.CharField(blank=True, help_text='A user-specified description of the transaction', max_length=100, null=True, verbose_name='user description'),
        ),
        migrations.AlterField(
            model_name='historicalbanktransaction',
            name='amount_credit',
            field=models.DecimalField(decimal_places=2, help_text='The credit (deposit) amount of the transaction', max_digits=12, verbose_name='credit amount'),
        ),
        migrations.AlterField(
            model_name='historicalbanktransaction',
            name='amount_debit',
            field=models.DecimalField(decimal_places=2, help_text='The debit (withdrawal) amount of the transaction', max_digits=12, verbose_name='debit amount'),
        ),
        migrations.AlterField(
            model_name='historicalbanktransaction',
            name='date_transaction',
            field=models.DateField(help_text='The date of the transaction', verbose_name='transaction date'),
        ),
        migrations.AlterField(
            model_name='historicalbanktransaction',
            name='description_bank',
            field=models.CharField(help_text='Description of the transaction as per the bank statement', max_length=100, verbose_name='bank description'),
        ),
        migrations.AlterField(
            model_name='historicalbanktransaction',
            name='description_user',
            field=models.CharField(blank=True, help_text='A user-specified description of the transaction', max_length=100, null=True, verbose_name='user description'),
        ),
        migrations.AlterField(
            model_name='historicalstatement',
            name='date_end',
            field=models.DateField(help_text='The last date the statement applies to', verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='historicalstatement',
            name='date_start',
            field=models.DateField(help_text='The first date the statement applies to', verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='account',
            field=models.ForeignKey(help_text='The account this statement belong to', on_delete=django.db.models.deletion.CASCADE, to='bank_transactions.Account'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='date_end',
            field=models.DateField(help_text='The last date the statement applies to', verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='statement',
            name='date_start',
            field=models.DateField(help_text='The first date the statement applies to', verbose_name='start date'),
        ),
    ]
