# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0005_auto_20171228_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmatch',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='am_attachment', to='documents.Attachment'),
        ),
        migrations.AlterField(
            model_name='attachmentmatch',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='am_bank_transaction', to='bank_transactions.BankTransaction'),
        ),
    ]
