# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0006_auto_20180114_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachmentmatch',
            name='transaction',
        ),
        migrations.RemoveField(
            model_name='historicalattachmentmatch',
            name='transaction',
        ),
        migrations.AddField(
            model_name='attachmentmatch',
            name='statement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='am_bank_transaction', to='bank_transactions.Statement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalattachmentmatch',
            name='statement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_transactions.Statement'),
        ),
    ]
