# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_transactions', '0007_auto_20180114_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='amount_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The credit (deposit) amount of the transaction', max_digits=12, verbose_name='credit amount'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='amount_debit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The debit (withdrawal) amount of the transaction', max_digits=12, verbose_name='debit amount'),
        ),
        migrations.AlterField(
            model_name='historicalbanktransaction',
            name='amount_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The credit (deposit) amount of the transaction', max_digits=12, verbose_name='credit amount'),
        ),
        migrations.AlterField(
            model_name='historicalbanktransaction',
            name='amount_debit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The debit (withdrawal) amount of the transaction', max_digits=12, verbose_name='debit amount'),
        ),
    ]
