# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-03 20:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FileField(upload_to='attachments')),
                ('date_uploads', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
