# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FileField(upload_to='attachments')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
