# Generated by Django 5.1.5 on 2025-01-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalbankstatementmatch',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical bank statement match', 'verbose_name_plural': 'historical bank statement matchs'},
        ),
        migrations.AlterModelOptions(
            name='historicalfinancialtransactionmatch',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical financial transaction match', 'verbose_name_plural': 'historical financial transaction matchs'},
        ),
        migrations.AlterField(
            model_name='historicalbankstatementmatch',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfinancialtransactionmatch',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
