# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_bank_transaction', to='bank_transactions.BankTransaction')),
            ],
        ),
    ]
