# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 05:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_transactions', '0001_initial'),
        ('bank_reconciliation', '0001_initial'),
        ('financial_transactions', '0002_auto_20180208_2222'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationmatch',
            name='bank_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_bank_transaction', to='bank_transactions.BankTransaction'),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='financial_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_financial_transaction', to='financial_transactions.FinancialTransaction'),
        ),
        migrations.AddField(
            model_name='historicalreconciliationmatch',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_transactions.BankTransaction'),
        ),
        migrations.AddField(
            model_name='historicalreconciliationmatch',
            name='financial_transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_transactions.FinancialTransaction'),
        ),
        migrations.AddField(
            model_name='historicalreconciliationmatch',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
