# Generated by Django 5.1.5 on 2025-01-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalreconciliationgroup',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical reconciliation group', 'verbose_name_plural': 'historical reconciliation groups'},
        ),
        migrations.AlterField(
            model_name='historicalreconciliationgroup',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
