# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_transactions', '0002_auto_20180209_2047'),
        ('bank_transactions', '0001_initial'),
        ('bank_reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationmatch',
            name='bank_transaction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rm_bank_transaction', to='bank_transactions.BankTransaction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='financial_transaction',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='rm_financial_transaction', to='financial_transactions.FinancialTransaction'),
            preserve_default=False,
        ),
    ]
