# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_reconciliation', '0001_initial'),
        ('financial_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationmatch',
            name='financial_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_financial_transaction', to='financial_transactions.FinancialTransaction'),
        ),
    ]
