# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_transactions', '0001_initial'),
        ('bank_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationmatch',
            name='financial_transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rm_financial_transaction', to='financial_transactions.FinancialTransaction'),
        ),
        migrations.AddField(
            model_name='historicalreconciliationmatch',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_transactions.BankTransaction'),
        ),
        migrations.AddField(
            model_name='historicalreconciliationmatch',
            name='financial_transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_transactions.FinancialTransaction'),
        ),
    ]
