# Generated by Django 2.0.3 on 2018-07-14 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_match_groups(apps, schema_editor):
    # Get the MatchGroup model
    MatchGroup = apps.get_model('bank_reconciliation', 'MatchGroup')

    # Get the ReconcilationMatch model and all its entries
    ReconcilationMatch = apps.get_model('bank_reconciliation', 'ReconciliationMatch')
    matches = ReconcilationMatch.objects.all()

    # Cycle through all the matches and assing them to groups
    for match in matches:
        match_found = False

        for match_group in MatchGroup.objects.all():
            for group in match_group.reconciliationmatch_set.all():
                if match.financial_transaction == group.financial_transaction or match.bank_transaction == group.bank_transaction:
                    # Match found, save it to this match_group
                    match.group = match_group
                    match.save()

                    match_found = True

        # No match found, create new group
        if match_found is False:
            # Create the group
            group = MatchGroup.objects.create()

            # Assign the new group to this match
            match.group = group
            match.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_reconciliation', '0004_historicalreconciliationmatch_history_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMatchGroup',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical match group',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='MatchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='historicalreconciliationmatch',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_reconciliation.MatchGroup'),
        ),
        migrations.AddField(
            model_name='reconciliationmatch',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_reconciliation.MatchGroup', null=True),
            preserve_default=False,
        ),
        migrations.RunPython(create_match_groups),
        migrations.AlterField(
            model_name='reconciliationmatch',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_reconciliation.MatchGroup'),
        )
    ]
