# Generated by Django 2.0.3 on 2018-07-14 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_match_groups(apps, schema_editor):
    # Get the MatchGroup model
    MatchGroup = apps.get_model('bank_reconciliation', 'MatchGroup')

    # Get the ReconcilationMatch model and all its entries
    ReconcilationMatch = apps.get_model('bank_reconciliation', 'ReconciliationMatch')
    matches = ReconcilationMatch.objects.all()

    # Cycle through all the matches and assing them to groups
    for match in matches:
        match_found = False

        for match_group in MatchGroup.objects.all():
            for group in match_group.reconciliationmatch_set.all():
                if match.financial_transaction == group.financial_transaction or match.bank_transaction == group.bank_transaction:
                    # Match found, save it to this match_group
                    match.group = match_group
                    match.save()

                    match_found = True

        # No match found, create new group
        if match_found is False:
            # Create the group
            group = MatchGroup.objects.create()

            # Assign the new group to this match
            match.group = group
            match.save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_reconciliation', '0005_auto_20180714_1345'),
    ]

    operations = [
        migrations.RunPython(create_match_groups),
    ]
