# Generated by Django 2.0.3 on 2018-07-14 20:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_reconciliation', '0005_auto_20180714_1345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalMatchGroup',
            new_name='HistoricalReconciliationGroup',
        ),
        migrations.RenameModel(
            old_name='MatchGroup',
            new_name='ReconciliationGroup',
        ),
        migrations.AlterModelOptions(
            name='historicalreconciliationgroup',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical reconciliation group'},
        ),
    ]
