# Generated by Django 2.0.3 on 2018-07-14 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bank_reconciliation', '0006_auto_20180714_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationmatch',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_reconciliation.MatchGroup'),
        )
    ]
