# Generated by Django 2.0.3 on 2018-07-14 21:23

from django.db import migrations


def add_reconcilation_groups(apps, schema_editor):
    # Get the models
    ReconciliationGroup = apps.get_model('bank_reconciliation', 'ReconciliationGroup')

    # Cycle through each reconciled transaction and add the reconcilation group
    for group in ReconciliationGroup.objects.all():
        for match in group.reconciliationmatch_set.all():
            # Add the group to the financial transaction
            match.financial_transaction.reconciled = group
            match.financial_transaction.save()

            # Add the group to the financial transaction
            match.bank_transaction.reconciled = group
            match.bank_transaction.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bank_reconciliation', '0006_auto_20180714_1457'),
    ]

    operations = [
        migrations.RunPython(add_reconcilation_groups),
    ]
