# Generated by Django 2.0.3 on 2018-07-14 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reconciliation', '0009_auto_20180714_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalreconciliationmatch',
            name='bank_transaction',
        ),
        migrations.RemoveField(
            model_name='historicalreconciliationmatch',
            name='financial_transaction',
        ),
        migrations.RemoveField(
            model_name='historicalreconciliationmatch',
            name='group',
        ),
        migrations.RemoveField(
            model_name='historicalreconciliationmatch',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='reconciliationmatch',
            name='bank_transaction',
        ),
        migrations.RemoveField(
            model_name='reconciliationmatch',
            name='financial_transaction',
        ),
        migrations.RemoveField(
            model_name='reconciliationmatch',
            name='group',
        ),
        migrations.DeleteModel(
            name='HistoricalReconciliationMatch',
        ),
        migrations.DeleteModel(
            name='ReconciliationMatch',
        ),
    ]
