# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialCodeMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('e', 'expense'), ('r', 'revenue')], default='e', help_text='The type of transaction', max_length=1)),
                ('memo', models.CharField(help_text='Details of the transaction', max_length=1000)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, verbose_name='submission date')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAttachmentMatch',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical attachment match',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFinancialCodeMatch',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical financial code match',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFinancialTransaction',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('e', 'expense'), ('r', 'revenue')], default='e', help_text='The type of transaction', max_length=1)),
                ('memo', models.CharField(help_text='Details of the transaction', max_length=1000)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, verbose_name='submission date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical financial transaction',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_item', models.DateField(default=django.utils.timezone.now, help_text='The date the item was purchased, cheque written, etc.', verbose_name='date')),
                ('description', models.CharField(help_text='A description of the item', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='The pre-tax dollar value', max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, default=0, help_text='The tax (GST/HST) dollar value', max_digits=12)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical item',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_item', models.DateField(default=django.utils.timezone.now, help_text='The date the item was purchased, cheque written, etc.', verbose_name='date')),
                ('description', models.CharField(help_text='A description of the item', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='The pre-tax dollar value', max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, default=0, help_text='The tax (GST/HST) dollar value', max_digits=12)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_transactions.FinancialTransaction')),
            ],
        ),
    ]
