# Generated by Django 2.0.3 on 2018-07-15 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank_reconciliation', '0001_initial'),
        ('financial_codes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payee_payers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialCodeMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_codes.FinancialCode')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('e', 'expense'), ('r', 'revenue')], default='e', help_text='The type of transaction', max_length=1)),
                ('memo', models.CharField(help_text='Overall summary of the transaction', max_length=1000)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, verbose_name='submission date')),
                ('payee_payer', models.ForeignKey(help_text='The individual, organization, or company this transaction applies to', on_delete=django.db.models.deletion.PROTECT, to='payee_payers.PayeePayer', verbose_name='payee or payer')),
                ('reconciled', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financialtransactions', to='bank_reconciliation.ReconciliationGroup')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalFinancialCodeMatch',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('financial_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_codes.FinancialCode')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical financial code match',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFinancialTransaction',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('e', 'expense'), ('r', 'revenue')], default='e', help_text='The type of transaction', max_length=1)),
                ('memo', models.CharField(help_text='Overall summary of the transaction', max_length=1000)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now, verbose_name='submission date')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payee_payer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payee_payers.PayeePayer')),
                ('reconciled', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='bank_reconciliation.ReconciliationGroup')),
            ],
            options={
                'verbose_name': 'historical financial transaction',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalItem',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date_item', models.DateField(default=django.utils.timezone.now, help_text='The date the item was purchased, cheque written, etc.', verbose_name='date')),
                ('description', models.CharField(help_text='A description of the item', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='The pre-tax dollar value', max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, default=0, help_text='The tax (GST/HST) dollar value', max_digits=12, verbose_name='GST/HST')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_transactions.FinancialTransaction')),
            ],
            options={
                'verbose_name': 'historical item',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_item', models.DateField(default=django.utils.timezone.now, help_text='The date the item was purchased, cheque written, etc.', verbose_name='date')),
                ('description', models.CharField(help_text='A description of the item', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='The pre-tax dollar value', max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, default=0, help_text='The tax (GST/HST) dollar value', max_digits=12, verbose_name='GST/HST')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_transactions.FinancialTransaction')),
            ],
        ),
        migrations.AddField(
            model_name='historicalfinancialcodematch',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_transactions.Item'),
        ),
        migrations.AddField(
            model_name='financialcodematch',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_transactions.Item'),
        ),
    ]
