# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 05:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financial_codes', '0002_auto_20180208_2222'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payee_payers', '0001_initial'),
        ('documents', '0001_initial'),
        ('financial_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalitem',
            name='transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_transactions.FinancialTransaction'),
        ),
        migrations.AddField(
            model_name='historicalfinancialtransaction',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfinancialtransaction',
            name='payee_payer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='payee_payers.PayeePayer'),
        ),
        migrations.AddField(
            model_name='historicalfinancialcodematch',
            name='financial_code',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_codes.FinancialCode'),
        ),
        migrations.AddField(
            model_name='historicalfinancialcodematch',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfinancialcodematch',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_transactions.Item'),
        ),
        migrations.AddField(
            model_name='historicalattachmentmatch',
            name='attachment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.Attachment'),
        ),
        migrations.AddField(
            model_name='historicalattachmentmatch',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalattachmentmatch',
            name='transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_transactions.FinancialTransaction'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='payee_payer',
            field=models.ForeignKey(help_text='The individual, organization, or company this transaction applies to', on_delete=django.db.models.deletion.PROTECT, to='payee_payers.PayeePayer', verbose_name='payee or payer'),
        ),
        migrations.AddField(
            model_name='financialcodematch',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_codes.FinancialCode'),
        ),
        migrations.AddField(
            model_name='financialcodematch',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_transactions.Item'),
        ),
        migrations.AddField(
            model_name='attachmentmatch',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Attachment'),
        ),
        migrations.AddField(
            model_name='attachmentmatch',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_transactions.FinancialTransaction'),
        ),
    ]
