# Generated by Django 2.0.3 on 2018-09-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_codes', '0001_initial'),
        ('financial_transactions', '0002_add_item_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='financial_codes',
            field=models.ManyToManyField(through='financial_transactions.FinancialCodeMatch', to='financial_codes.FinancialCode'),
        ),
    ]
