# Generated by Django 2.0.3 on 2018-07-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_transactions', '0002_auto_20180216_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialtransaction',
            name='memo',
            field=models.CharField(help_text='Overall summary of the transaction', max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalfinancialtransaction',
            name='memo',
            field=models.CharField(help_text='Overall summary of the transaction', max_length=1000),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The tax (GST/HST) dollar value', max_digits=12, verbose_name='GST/HST'),
        ),
        migrations.AlterField(
            model_name='item',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The tax (GST/HST) dollar value', max_digits=12, verbose_name='GST/HST'),
        ),
    ]
