# Generated by Django 2.0.3 on 2018-10-01 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_transactions', '0003_add_item_code_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialtransaction',
            name='submission_notes',
            field=models.CharField(blank=True, help_text='Additional notes and details about this submission.', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalfinancialtransaction',
            name='submission_notes',
            field=models.CharField(blank=True, help_text='Additional notes and details about this submission.', max_length=1000, null=True),
        ),
    ]
