# Generated by Django 5.1.5 on 2025-01-26 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_transactions', '0005_updating_historical_transaction-field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalfinancialcodematch',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical financial code match', 'verbose_name_plural': 'historical financial code matchs'},
        ),
        migrations.AlterModelOptions(
            name='historicalfinancialtransaction',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical financial transaction', 'verbose_name_plural': 'historical financial transactions'},
        ),
        migrations.AlterModelOptions(
            name='historicalitem',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical item', 'verbose_name_plural': 'historical items'},
        ),
        migrations.AlterField(
            model_name='historicalfinancialcodematch',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalfinancialtransaction',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
