# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 03:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payee_payers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payeepayer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
