# Generated by Django 2.0.3 on 2018-07-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payee_payers', '0003_auto_20180219_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayeepayer',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('i', 'inactive')], default='a', help_text='Whether this individual has recent expense or revenue activity', max_length=2),
        ),
        migrations.AlterField(
            model_name='payeepayer',
            name='status',
            field=models.CharField(choices=[('a', 'active'), ('i', 'inactive')], default='a', help_text='Whether this individual has recent expense or revenue activity', max_length=2),
        ),
    ]
