# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20180103_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentmatch',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Attachment'),
        ),
        migrations.AlterField(
            model_name='attachmentmatch',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_item',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date the item was purchased, cheque written, etc.', verbose_name='date'),
        ),
    ]
