# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.FileField(upload_to='user_uploads')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='PDF',
            new_name='FinalAttachment',
        ),
        migrations.RenameField(
            model_name='finalattachment',
            old_name='date_uploads',
            new_name='date_uploaded',
        ),
    ]
