# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20171203_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinalAttachment',
            new_name='Attachment',
        ),
        migrations.DeleteModel(
            name='OriginalFile',
        ),
    ]
