# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 03:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_codes', '0002_auto_20171226_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialcodegroup',
            name='financial_code_system',
            field=models.ForeignKey(default=1, help_text='The financial code system that this group applies to', on_delete=django.db.models.deletion.CASCADE, to='financial_codes.FinancialCodeSystem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfinancialcodegroup',
            name='financial_code_system',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_codes.FinancialCodeSystem'),
        ),
        migrations.AlterField(
            model_name='budgetyear',
            name='date_end',
            field=models.DateField(help_text='Last day of the budget year', verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='budgetyear',
            name='date_start',
            field=models.DateField(help_text='First day of the budget year', verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='historicalbudgetyear',
            name='date_end',
            field=models.DateField(help_text='Last day of the budget year', verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='historicalbudgetyear',
            name='date_start',
            field=models.DateField(help_text='First day of the budget year', verbose_name='start date'),
        ),
    ]
