# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-30 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_codes', '0003_auto_20171229_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetyear',
            name='financial_code_system',
            field=models.ForeignKey(default=1, help_text='The financial code system that this budget year applies to', on_delete=django.db.models.deletion.CASCADE, to='financial_codes.FinancialCodeSystem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbudgetyear',
            name='financial_code_system',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_codes.FinancialCodeSystem'),
        ),
    ]
