# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_codes', '0004_auto_20171229_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(help_text='First day this assignment applies to', verbose_name='start date')),
                ('date_end', models.DateField(blank=True, help_text='Last day this assignment applies to (leave blank for no end date)', null=True, verbose_name='end date')),
                ('financial_code_system', models.ForeignKey(help_text='The financial code system to assign', on_delete=django.db.models.deletion.CASCADE, to='financial_codes.FinancialCodeSystem')),
            ],
        ),
    ]
