# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financial_codes', '0005_systemassignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemassignment',
            name='financial_code_system',
        ),
        migrations.RemoveField(
            model_name='financialcodesystem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialcodesystem',
            name='status',
        ),
        migrations.AddField(
            model_name='financialcodesystem',
            name='date_end',
            field=models.DateField(blank=True, help_text='Last day this assignment applies to (leave blank for no end date)', null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='financialcodesystem',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='First day this assignment applies to', verbose_name='start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfinancialcodesystem',
            name='date_end',
            field=models.DateField(blank=True, help_text='Last day this assignment applies to (leave blank for no end date)', null=True, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='historicalfinancialcodesystem',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, help_text='First day this assignment applies to', verbose_name='start date'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SystemAssignment',
        ),
    ]
