# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial_codes', '0006_auto_20180103_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialcode',
            old_name='code_group',
            new_name='financial_code_group',
        ),
        migrations.RenameField(
            model_name='historicalfinancialcode',
            old_name='code_group',
            new_name='financial_code_group',
        ),
        migrations.RemoveField(
            model_name='financialcode',
            name='budget_year',
        ),
        migrations.RemoveField(
            model_name='financialcode',
            name='code_system',
        ),
        migrations.RemoveField(
            model_name='financialcodegroup',
            name='financial_code_system',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialcode',
            name='budget_year',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialcode',
            name='code_system',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialcodegroup',
            name='financial_code_system',
        ),
        migrations.AddField(
            model_name='financialcodegroup',
            name='budget_year',
            field=models.ForeignKey(default=1, help_text='The budget year that this group applies to', on_delete=django.db.models.deletion.CASCADE, to='financial_codes.BudgetYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfinancialcodegroup',
            name='budget_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_codes.BudgetYear'),
        ),
    ]
