# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-23 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payee_payer', '0002_auto_20171222_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographics',
            name='name',
            field=models.CharField(help_text='The individual, company, or organization name', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='name',
            field=models.CharField(db_index=True, help_text='The individual, company, or organization name', max_length=256),
        ),
    ]
