# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payee_payer', '0003_auto_20171222_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
        migrations.AlterField(
            model_name='demographics',
            name='fax',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='fax number'),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='name',
            field=models.CharField(help_text='The individual, company, or organization name', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='demographics',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='fax',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='fax number'),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='name',
            field=models.CharField(db_index=True, help_text='The individual, company, or organization name', max_length=250),
        ),
        migrations.AlterField(
            model_name='historicaldemographics',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='phone number'),
        ),
    ]
