# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-10 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name to identify the investment', max_length=256)),
                ('date_invested', models.DateField(help_text='Date of initial investment')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Initial amount invested', max_digits=12)),
                ('rate', models.CharField(help_text='Details on rate, term duration, etc.', max_length=256)),
            ],
        ),
    ]
