# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-11 02:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInvestment',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Name to identify the investment', max_length=256)),
                ('date_invested', models.DateField(help_text='Date of initial investment')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Initial amount invested', max_digits=12)),
                ('rate', models.CharField(help_text='Details on rate, term duration, etc.', max_length=256)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical investment',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
