# Generated by Django 2.0.3 on 2018-07-15 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_investment', models.DateField()),
                ('detail_status', models.CharField(choices=[('v', 'invested'), ('m', 'matured'), ('i', 'interest paid'), ('c', 'cancelled')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='The amount invested, matured, or paid out', max_digits=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalinvestment',
            name='amount_invested',
        ),
        migrations.RemoveField(
            model_name='historicalinvestment',
            name='amount_matured',
        ),
        migrations.RemoveField(
            model_name='historicalinvestment',
            name='date_invested',
        ),
        migrations.RemoveField(
            model_name='historicalinvestment',
            name='date_matured',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='amount_invested',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='amount_matured',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='date_invested',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='date_matured',
        ),
        migrations.AddField(
            model_name='investmentdetail',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investmentdetails', to='investments.Investment'),
        ),
    ]
