# Generated by Django 2.0.3 on 2018-07-08 13:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_historicalinvestment_history_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestment',
            name='amount_matured',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount currently or at maturation', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalinvestment',
            name='date_matured',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of maturation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='amount_matured',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount currently or at maturation', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='date_matured',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date of maturation'),
            preserve_default=False,
        ),
    ]
