# Generated by Django 2.0.3 on 2018-07-15 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_reconciliation', '0001_initial'),
        ('investments', '0002_investment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdetail',
            name='reconciled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investmentdetailss', to='bank_reconciliation.ReconciliationGroup'),
        ),
    ]
