# Generated by Django 2.0.3 on 2018-07-15 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_add_reconcilation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentdetail',
            name='reconciled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investmentdetails', to='bank_reconciliation.ReconciliationGroup'),
        ),
    ]
