# Generated by Django 2.0.3 on 2018-07-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_auto_20180708_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestment',
            name='amount_initial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Initial amount invested', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='amount_initial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Initial amount invested', max_digits=12),
            preserve_default=False,
        ),
    ]
