# Generated by Django 2.0.3 on 2018-07-08 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_auto_20180708_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvestment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='amount',
        ),
    ]
