# Generated by Django 2.0.3 on 2018-07-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_auto_20180708_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalinvestment',
            old_name='amount_initial',
            new_name='amount_invested',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='amount_initial',
            new_name='amount_invested',
        ),
    ]
