# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-10 21:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payee_payer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial_codes', '0001_initial'),
        ('documents', '0003_auto_20171210_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='documents.Attachment')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialCodeMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='financial_codes.FinancialCode')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAttachmentMatch',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('attachment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.Attachment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical attachment match',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFinancialCodeMatch',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('financial_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial_codes.FinancialCode')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical financial code match',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_item', models.DateField(help_text='The date the item was purchased, cheque written, etc.')),
                ('description', models.CharField(help_text='A description of the item', max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The pre-tax dollar value', max_digits=12)),
                ('gst', models.DecimalField(decimal_places=2, help_text='The tax (GST/HST) dollar value', max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('p', 'Payable'), ('r', 'Receivable')], help_text='The type of transaction', max_length=1)),
                ('memo', models.CharField(help_text='Details of the transaction', max_length=1000)),
                ('date_submitted', models.DateField(default=django.utils.timezone.now)),
                ('payee_payer', models.ForeignKey(help_text='The individual, organization, or company this transaction applies to', on_delete=django.db.models.deletion.PROTECT, to='payee_payer.Demographics')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
        migrations.AddField(
            model_name='historicalfinancialcodematch',
            name='item',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transactions.Item'),
        ),
        migrations.AddField(
            model_name='historicalattachmentmatch',
            name='transaction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transactions.Transaction'),
        ),
        migrations.AddField(
            model_name='financialcodematch',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.Item'),
        ),
        migrations.AddField(
            model_name='attachmentmatch',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.Transaction'),
        ),
    ]
