# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('e', 'expense'), ('r', 'revenue')], default='e', help_text='The type of transaction', max_length=1),
        ),
    ]
