# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20171226_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date_item',
            field=models.DateField(help_text='The date the item was purchased, cheque written, etc.', verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_submitted',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='submission date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payee_payer',
            field=models.ForeignKey(help_text='The individual, organization, or company this transaction applies to', on_delete=django.db.models.deletion.PROTECT, to='payee_payer.Demographics', verbose_name='payee or payer'),
        ),
    ]
