# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-06 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20180106_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialcodematch',
            name='financial_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial_codes.FinancialCode'),
        ),
        migrations.AlterField(
            model_name='financialcodematch',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Item'),
        ),
    ]
